"""
Signal analysis for vibration / sound / temperature / current.

Outputs are designed to be human-readable AND machine-readable:
- numeric features for the risk engine
- a structured summary for LLM prompts
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any

import numpy as np
import pandas as pd
from scipy.integrate import trapezoid
from scipy.signal import welch


SAMPLE_RATE_HZ = 1000.0  # generated demo data sample rate

VIB_AXES = ("vibration_x", "vibration_y", "vibration_z")
PRIMARY_AXIS = "vibration_z"


@dataclass
class FFTPeak:
    frequency_hz: float
    amplitude: float

    def to_dict(self) -> dict[str, float]:
        return {"frequency_hz": round(self.frequency_hz, 2), "amplitude": round(self.amplitude, 5)}


@dataclass
class SignalFeatures:
    vibration_rms: float
    vibration_peak: float
    vibration_axes_rms: dict[str, float]
    sound_mean_db: float
    sound_max_db: float
    temperature_max_c: float
    temperature_trend_c_per_s: float
    current_mean_a: float
    current_trend_a_per_s: float
    fft_peaks: list[FFTPeak] = field(default_factory=list)
    bearing_band_energy_ratio: float = 0.0  # 100-300Hz vs total
    # Input-bundle metadata — surfaces "did we have enough data to trust this?"
    # to the Intake/Governance agents downstream. Defaults make older
    # serialised features still round-trip.
    sample_count: int = 0
    duration_seconds: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["fft_peaks"] = [p if isinstance(p, dict) else p.to_dict() for p in self.fft_peaks]
        # round floats for readability
        for k, v in list(d.items()):
            if isinstance(v, float):
                d[k] = round(v, 4)
        d["vibration_axes_rms"] = {k: round(v, 5) for k, v in d["vibration_axes_rms"].items()}
        return d


def _linear_trend(values: np.ndarray, t: np.ndarray) -> float:
    """Slope of the best-fit line, in units per second."""
    if values.size < 2:
        return 0.0
    slope, _ = np.polyfit(t, values, 1)
    return float(slope)


def _fft_peaks(signal: np.ndarray, fs: float, top_k: int = 3) -> tuple[list[FFTPeak], np.ndarray, np.ndarray]:
    """Return top-k peaks plus the full spectrum (for plotting)."""
    n = signal.size
    if n < 4:
        return [], np.array([]), np.array([])
    # Detrend
    centered = signal - signal.mean()
    spectrum = np.abs(np.fft.rfft(centered)) / n
    freqs = np.fft.rfftfreq(n, d=1.0 / fs)
    # Skip DC
    if spectrum.size > 1:
        spec = spectrum[1:]
        f = freqs[1:]
    else:
        spec, f = spectrum, freqs
    if spec.size == 0:
        return [], freqs, spectrum
    idx = np.argpartition(spec, -min(top_k, spec.size))[-top_k:]
    idx = idx[np.argsort(-spec[idx])]
    peaks = [FFTPeak(frequency_hz=float(f[i]), amplitude=float(spec[i])) for i in idx]
    return peaks, freqs, spectrum


def _bearing_band_ratio(signal: np.ndarray, fs: float) -> float:
    """Energy in 100–300Hz (bearing-fault region) over total energy.

    Higher ratio → more of the vibration energy sits in the bearing-fault band.
    """
    if signal.size < 16:
        return 0.0
    f, pxx = welch(signal - signal.mean(), fs=fs, nperseg=min(256, signal.size))
    total = float(trapezoid(pxx, f))
    if total <= 0:
        return 0.0
    mask = (f >= 100.0) & (f <= 300.0)
    band = float(trapezoid(pxx[mask], f[mask])) if mask.any() else 0.0
    return band / total


def analyze(df: pd.DataFrame, fs: float = SAMPLE_RATE_HZ) -> SignalFeatures:
    """Compute features from a sensor dataframe.

    The dataframe must contain at least the columns generated by
    `data/generate_demo_data.py`. Missing optional columns degrade
    gracefully to zeros so partial inputs don't crash the pipeline.
    """
    t = df["timestamp"].to_numpy() if "timestamp" in df.columns else np.arange(len(df)) / fs

    axes_rms: dict[str, float] = {}
    for axis in VIB_AXES:
        if axis in df.columns:
            axes_rms[axis] = float(np.sqrt(np.mean(df[axis].to_numpy() ** 2)))
        else:
            axes_rms[axis] = 0.0

    primary = df[PRIMARY_AXIS].to_numpy() if PRIMARY_AXIS in df.columns else np.zeros(len(df))
    vib_rms = float(np.sqrt(np.mean(primary ** 2))) if primary.size else 0.0
    vib_peak = float(np.max(np.abs(primary))) if primary.size else 0.0

    sound = df["sound_level"].to_numpy() if "sound_level" in df.columns else np.zeros(len(df))
    temp = df["temperature"].to_numpy() if "temperature" in df.columns else np.zeros(len(df))
    current = df["current"].to_numpy() if "current" in df.columns else np.zeros(len(df))

    peaks, _, _ = _fft_peaks(primary, fs=fs, top_k=3)
    band_ratio = _bearing_band_ratio(primary, fs=fs)

    n = int(len(df))
    if t.size >= 2:
        duration = float(t[-1] - t[0])
    else:
        duration = float(n) / fs if fs > 0 else 0.0

    return SignalFeatures(
        vibration_rms=vib_rms,
        vibration_peak=vib_peak,
        vibration_axes_rms=axes_rms,
        sound_mean_db=float(np.mean(sound)) if sound.size else 0.0,
        sound_max_db=float(np.max(sound)) if sound.size else 0.0,
        temperature_max_c=float(np.max(temp)) if temp.size else 0.0,
        temperature_trend_c_per_s=_linear_trend(temp, t) if temp.size else 0.0,
        current_mean_a=float(np.mean(current)) if current.size else 0.0,
        current_trend_a_per_s=_linear_trend(current, t) if current.size else 0.0,
        fft_peaks=peaks,
        bearing_band_energy_ratio=band_ratio,
        sample_count=n,
        duration_seconds=duration,
    )


def spectrum_for_plot(df: pd.DataFrame, axis: str = PRIMARY_AXIS, fs: float = SAMPLE_RATE_HZ) -> tuple[np.ndarray, np.ndarray]:
    """Return (frequencies, amplitudes) for FFT plotting on the chosen axis."""
    if axis not in df.columns:
        return np.array([]), np.array([])
    _, freqs, spectrum = _fft_peaks(df[axis].to_numpy(), fs=fs)
    return freqs, spectrum
